---
- name: Copier docker-compose.yml sur l'h么te
  copy:
    src: ../../docker/docker-compose.yml
    dest: /home/{{ ansible_user }}/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Copier prometheus.yml sur l'h么te
  copy:
    src: ../../docker/prometheus.yml
    dest: /home/{{ ansible_user }}/prometheus.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Lancer la stack Docker Compose V2
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}
    state: present

- name: Copier le dossier backend sur l'h么te
  copy:
    src: ../../docker/backend
    dest: /home/{{ ansible_user }}/backend
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copier le dossier frontend sur l'h么te
  copy:
    src: ../../docker/frontend
    dest: /home/{{ ansible_user }}/frontend
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
