version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: infra_postgres
    environment:
      POSTGRES_USER: infra
      POSTGRES_PASSWORD: infra
      POSTGRES_DB: infra_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:latest
    container_name: infra_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  backend:
    build: ./backend
    container_name: infra_backend
    environment:
      DB_HOST: postgres
      DB_NAME: infra_db
      DB_USER: infra
      DB_PASSWORD: infra
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  agent1:
    image: alpine:latest
    container_name: infra_agent1
    command: >
      sh -c "while true; do curl -s -X POST -H 'Content-Type: application/json' -d '{\"cpu\":10}' http://backend:5000/metrics; sleep 10; done"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: infra_grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  frontend:
    build: ./frontend
    container_name: infra_frontend
    ports:
      - "8080:80"

volumes:
  pgdata:
